name: dart_api_download_video
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/Pedro-111/YTDownloader

environment:
  sdk: ^3.1.2

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
